name: Clone External Repository on Push

on:
  push:
    branches:
      - updates-to-merge

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          path: updates-to-merge

      #TODO replace it downloading pipy private package
      - name: Clone external repository to get ddlforge-cli
        uses: actions/checkout@v4
        with:
          ref: main
          repository: giorgiogrillini-capgemini/ddlforge-cli
          token: ${{ secrets.PAT_DDLFORGE }}
          path: ddlforge-cli

      #TODO use cache!!
      - name: Installing venv and launching ddlforge-cli
        run: |
          cd ddlforge-cli
          sudo apt-get update -y
          sudo apt-get install -y pipx
          pipx ensurepath
          pipx install uv
          uv python install 3.12
          uv venv --python 3.12
          source .venv/bin/activate
          uv pip install -e .
          echo "producing settings.yaml"
          ddlforge settings --google_project_id premi0436563-gitenter\
           --policy_location europe-west9 --write_to settings.yaml\
           --env_label dev --key_ring_name datacloud-cstore-europe-west9-main-dev\
           --json_schema_asset_dir table-schemas 1918308629030057169
          echo "producing settings.yaml"
          ddlforge tf-table-configs src/tests/sample_2.ddl settings.yaml ./tf


