name: Clone External Repository on Push

on:
  push:
    branches:
      - updates-to-merge

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Clone external repository
        run: |
          git clone https://github.com/giorgiogrillini-capgemini/ddlforge-cli.git