name: Clone External Repository on Push

on:
  push:
    branches:
      - updates-to-merge

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: updates-to-merge

      #TODO replace it downloading pipy private package
      - name: Clone external repository to get ddlforge-cli
        uses: actions/checkout@v4
        with:
          repository: giorgiogrillini-capgemini/ddlforge-cli
          token: ${{ secrets.PAT_DDLFORGE }}
